/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppTimetableRouteImport } from './routes/app.timetable'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppPlacesRouteImport } from './routes/app.places'
import { Route as AppLocationRouteImport } from './routes/app.location'
import { Route as AppFriendsRouteImport } from './routes/app.friends'
import { Route as AppFriendIdRouteImport } from './routes/app.friend.$id'
import { Route as AppChatIdRouteImport } from './routes/app.chat.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppTimetableRoute = AppTimetableRouteImport.update({
  id: '/timetable',
  path: '/timetable',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppPlacesRoute = AppPlacesRouteImport.update({
  id: '/places',
  path: '/places',
  getParentRoute: () => AppRoute,
} as any)
const AppLocationRoute = AppLocationRouteImport.update({
  id: '/location',
  path: '/location',
  getParentRoute: () => AppRoute,
} as any)
const AppFriendsRoute = AppFriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => AppRoute,
} as any)
const AppFriendIdRoute = AppFriendIdRouteImport.update({
  id: '/friend/$id',
  path: '/friend/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppChatIdRoute = AppChatIdRouteImport.update({
  id: '/chat/$id',
  path: '/chat/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/friends': typeof AppFriendsRoute
  '/app/location': typeof AppLocationRoute
  '/app/places': typeof AppPlacesRoute
  '/app/profile': typeof AppProfileRoute
  '/app/timetable': typeof AppTimetableRoute
  '/app/': typeof AppIndexRoute
  '/app/chat/$id': typeof AppChatIdRoute
  '/app/friend/$id': typeof AppFriendIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app/friends': typeof AppFriendsRoute
  '/app/location': typeof AppLocationRoute
  '/app/places': typeof AppPlacesRoute
  '/app/profile': typeof AppProfileRoute
  '/app/timetable': typeof AppTimetableRoute
  '/app': typeof AppIndexRoute
  '/app/chat/$id': typeof AppChatIdRoute
  '/app/friend/$id': typeof AppFriendIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/friends': typeof AppFriendsRoute
  '/app/location': typeof AppLocationRoute
  '/app/places': typeof AppPlacesRoute
  '/app/profile': typeof AppProfileRoute
  '/app/timetable': typeof AppTimetableRoute
  '/app/': typeof AppIndexRoute
  '/app/chat/$id': typeof AppChatIdRoute
  '/app/friend/$id': typeof AppFriendIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/app/friends'
    | '/app/location'
    | '/app/places'
    | '/app/profile'
    | '/app/timetable'
    | '/app/'
    | '/app/chat/$id'
    | '/app/friend/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/app/friends'
    | '/app/location'
    | '/app/places'
    | '/app/profile'
    | '/app/timetable'
    | '/app'
    | '/app/chat/$id'
    | '/app/friend/$id'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/app/friends'
    | '/app/location'
    | '/app/places'
    | '/app/profile'
    | '/app/timetable'
    | '/app/'
    | '/app/chat/$id'
    | '/app/friend/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/timetable': {
      id: '/app/timetable'
      path: '/timetable'
      fullPath: '/app/timetable'
      preLoaderRoute: typeof AppTimetableRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/places': {
      id: '/app/places'
      path: '/places'
      fullPath: '/app/places'
      preLoaderRoute: typeof AppPlacesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/location': {
      id: '/app/location'
      path: '/location'
      fullPath: '/app/location'
      preLoaderRoute: typeof AppLocationRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/friends': {
      id: '/app/friends'
      path: '/friends'
      fullPath: '/app/friends'
      preLoaderRoute: typeof AppFriendsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/friend/$id': {
      id: '/app/friend/$id'
      path: '/friend/$id'
      fullPath: '/app/friend/$id'
      preLoaderRoute: typeof AppFriendIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/chat/$id': {
      id: '/app/chat/$id'
      path: '/chat/$id'
      fullPath: '/app/chat/$id'
      preLoaderRoute: typeof AppChatIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppFriendsRoute: typeof AppFriendsRoute
  AppLocationRoute: typeof AppLocationRoute
  AppPlacesRoute: typeof AppPlacesRoute
  AppProfileRoute: typeof AppProfileRoute
  AppTimetableRoute: typeof AppTimetableRoute
  AppIndexRoute: typeof AppIndexRoute
  AppChatIdRoute: typeof AppChatIdRoute
  AppFriendIdRoute: typeof AppFriendIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppFriendsRoute: AppFriendsRoute,
  AppLocationRoute: AppLocationRoute,
  AppPlacesRoute: AppPlacesRoute,
  AppProfileRoute: AppProfileRoute,
  AppTimetableRoute: AppTimetableRoute,
  AppIndexRoute: AppIndexRoute,
  AppChatIdRoute: AppChatIdRoute,
  AppFriendIdRoute: AppFriendIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
